# Generated by Django 4.1.1 on 2022-11-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0002_sendemail_delete_send_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('years', models.IntegerField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('district', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
