# Generated by Django 4.1.1 on 2022-11-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0003_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='years',
            field=models.IntegerField(),
        ),
    ]
